
version: '3'

services:

    ubooquity:
        image: linuxserver/ubooquity:latest
        container_name: ubooquity
        ports:
            - "2202:2202"
            - "2203:2203"
        volumes:
            - ${CONFIG}/ubooquity:/config
            - ${DATA}/ubooquity_books:/books
            - ${DATA}/Comics:/comics
        environment:
            - PGID
            - PUID
            - TZ
        labels:
            com.centurylinklabs.watchtower.enable: "true"
        restart: unless-stopped
