---
- name: Install pacman packages ({{ package_set }})
  pacman:
    name: "{{ pacman_packages }}"
    state: present

- name: Install aur packages ({{ package_set }})
  become: false
  yay:
    name: "{{ item }}"
    state: present
  with_items: "{{ aur_packages }}"

- name: Install snap packages {{ package_set }}
  community.general.snap:
    name: "{{ item}}"
    state: present
  with_items: "{{ snap_packages }}"
