---
- name: Install Kodi
  pacman:
    name:
      - xfce4  # I shouldn't need this but it's an easy way to get X11
      - kodi
      - kodi-x11
    state: present

- name: Install Kodi AUR Service
  become: false
  yay:
    name: kodi-standalone-service
    state: present

- name: Enable kodi
  service:
    name: kodi-x11.service
    enabled: true
    state: "started"

- name: Copy advanced settings to connect to db
  template:
    src: var--lib--kodi--.kodi--userdata--advancedsettings.xml.j2
    dest: /var/lib/kodi/.kodi/userdata/advancedsettings.xml
    owner: kodi
    group: kodi
    mode: 0644
    backup: true