# Eventually I might need to add more roles so I can customize my builds
# This is fine for now though

all:
    hosts:
        macarch:
            vars:
                ansible_user: ansible
                ansible_python_interpreter: "{{ansible_playbook_python}}"
