version: "3"

services:
    sabnzbd:
        image: linuxserver/sabnzbd:latest
        container_name: sabnzbd
        hostname: sabnzbd
        ports:
            - "8082:8080"
        volumes:
            - ${CONFIG}/sabnzbd:/config
            - ${DOWNLOAD}/complete:/downloads
            - ${DOWNLOAD}/incomplete:/incomplete-downloads
            - ${DOWNLOAD}/watch:/watch
        environment:
            - PGID
            - PUID
            - TZ
        labels:
            com.centurylinklabs.watchtower.enable: "true"
        restart: unless-stopped

    nzbhydra:
        image: linuxserver/nzbhydra2:latest
        container_name: nzbhydra
        hostname: nzbhydra
        ports:
            - "5076:5076"
        volumes:
            - ${CONFIG}/nzbhydra:/config
            - ${DOWNLOAD}/complete:/downloads
        environment:
            - PGID
            - PUID
            - TZ
        labels:
            com.centurylinklabs.watchtower.enable: "true"
        restart: unless-stopped

    sonarr:
        image: linuxserver/sonarr:latest
        container_name: sonarr
        hostname: sonarr
        ports:
            - "8989:8989"
        volumes:
            - ${CONFIG}/sonarr:/config
            - ${DOWNLOAD}/complete:/downloads
            - ${DATA}/TV:/tv
        environment:
            - PGID
            - PUID
            - TZ
        labels:
            com.centurylinklabs.watchtower.enable: "true"
        restart: unless-stopped

    radarr:
        image: linuxserver/radarr:latest
        container_name: radarr
        hostname: radarr
        ports:
            - "7878:7878"
        volumes:
            - ${CONFIG}/radarr:/config
            - ${DOWNLOAD}/complete:/downloads
            - ${DATA}/Movies:/movies
        environment:
            - PGID
            - PUID
            - TZ
        labels:
            com.centurylinklabs.watchtower.enable: "true"
        restart: unless-stopped

    mylar:
        image: linuxserver/mylar3:latest
        container_name: mylar
        hostname: mylar
        ports:
            - "8090:8090"
        volumes:
            - ${CONFIG}/mylar:/config/mylar
            - ${DOWNLOAD}/complete:/downloads
            - ${DATA}/Comics:/comics
        environment:
            - PGID
            - PUID
            - TZ
        labels:
            com.centurylinklabs.watchtower.enable: "true"
        restart: unless-stopped
