---
- name: Clone public dotfiles
  git:
    repo: git@github.com:ianepreston/dots.git
    version: main
    key_file: /home/ipreston/.ssh/ed25519_github
    dest: /home/ipreston/.dotfiles

- name: Clone private dotfiles
  git:
    repo: git@github.com:ianepreston/private_dots.git
    version: main
    key_file: /home/ipreston/.ssh/ed25519_github
    dest: /home/ipreston/.private_dotfiles