---
- name: Install GNOME
  pacman:
    name:
      - gnome
      - dconf-editor
      - gnome-tweaks
    state: present

- name: Remove GNOME bloat
  pacman:
    name:
      - epiphany
      - gedit
      - gnome-contacts
      - gnome-books
      - gnome-boxes
      - gnome-documents
      - gnome-maps
      - gnome-music
      - gnome-photos
      - gnome-remote-desktop
      - orca
      - rygel
      - simple-scan
      - totem
    state: absent

- name: Install GNOME AUR Tools
  become: false
  yay:
    name: "{{ item }}"
    state: present
  with_items:
      - gnome-shell-extension-material-shell-git

