---
- name: Enable display manager
  service: 
    name: gdm.service
    state: started
    enabled: true

- name: Don't show ansible user on the login page
  template:
    src: var-lib-AccountsService-users--ansible.j2
    dest: /var/lib/AccountsService/users/ansible
    owner: root
    group: root
    mode: 0640
    backup: false

- name: Install material shell
  become: false
  yay:
    name: gnome-shell-extension-material-shell
    state: present

- name: Enable material shell
  become_user: ipreston
  command: gnome-extensions enable material-shell@papyelgringo