---
# This first part just replicates what was done in the base install script
# The exception is the SSH role.  It can potentially lock you out of a machine
# by a misconfigured SSH config so it is run here.  If it causes issues in this
# main script it can be removed.
- name: Bootstrap Setup
  hosts: all
  become: true
  vars_files:
    - vars/bootstrap.yml
  roles:
    - hostname
    - pacman-config
    - upgrade
    - install-applications
    - bootloader-config
    - sudo
    - ansible-user
    - vagrant-user
    - keymap
    - time
    - locale
    - ssh
