version: "3"

services:
    watchtower:
        image: containrrr/watchtower:latest
        command: --cleanup --label-enable --schedule="0 2 * * *"
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            com.centurylinklabs.watchtower.enable: "true"
        restart: unless-stopped

    unifi-controller:
        image: linuxserver/unifi-controller:latest
        container_name: unifi-controller
        hostname: unifi-controller
        ports:
              - 3478:3478/udp
              - 10001:10001/udp
              - 8080:8080
              - 8081:8081
              - 8443:8443
              - 8843:8843
              - 8880:8880
              - 6789:6789
        volumes:
            - ${CONFIG}/unifi:/config
        environment:
            - PGID
            - PUID
            - TZ
            - MEM_LIMIT=1024M # optional
        labels:
            com.centurylinklabs.watchtower.enable: "true"
        restart: unless-stopped
    
    resilio-sync:
        image: linuxserver/resilio-sync
        container_name: resilio-sync
        environment:
        - PUID
        - PGID
        - TZ
        - UMASK_SET=022
        volumes:
        - ${CONFIG}/resilio:/config
        - ${CONFIG}/resilio/downloads:/downloads
        - /:/sync
        ports:
        - 8888:8888
        - 55555:55555
        restart: unless-stopped